# Generated automatically from Makefile.in by configure.
#
#	Makefile for ne3
#

prefix = /usr/local
OLD_DOCDIR = ${prefix}/share/doc/nxedit/old_doc
top_srcdir = ..
mkinstalldirs = /bin/sh $(top_srcdir)/mkinstalldirs
INSTALL= /usr/bin/install -c
INSTALL_DATA= ${INSTALL} -m 644

INSS = HISTORY Install NE.DOC README TECHKNOW ne.cat ne.man nxrc
TARS= $(INSS) Makefile.in

all:

depend:

clean:

distclean:
	rm -f Makefile

tar: $(TARS)
	@echo $(TARS) | tr [:space:] "\n" | sed -e s:^:$(ARC): | sort >> ../lists.tmp

install:
#	@$(mkinstalldirs) $(OLD_DOCDIR)
#	@set -e; for i in $(INSS); \
#	do (echo "install $$i" ;  $(INSTALL_DATA) $$i $(OLD_DOCDIR)/$$i); done
