#define	WAITING_MSG				(sysinfo.japanesef ? "しばらくお待ちください。":"Please Wait")
#define	SEARCHING_MSG			(sysinfo.japanesef ? "検索中":"Searching")
#define	NOT_FOUND_MSG			(sysinfo.japanesef ? "見つかりませんでした。":"Not Found")
#define	FOUND_MSG				(sysinfo.japanesef ? "見つかりました。":"Found")
#define	SAVEING_MSG				(sysinfo.japanesef ? "保存中":"Saveing")
#define	SAVESUCCESS_MSG			(sysinfo.japanesef ? "保存しました。":"Save success")
#define	NEWFILE_MSG				(sysinfo.japanesef ? "新しいファイルです。":"New File")
#define	READING_MSG				(sysinfo.japanesef ? "読み込み中":"Reading")
#define	CNTRL_INPUT_MSG			(sysinfo.japanesef ? "制御文字入力 (^x) ":"Input CONTROL Character (^x)")
#define	REPLACED_MSG			(sysinfo.japanesef ? "置換しました":"Replaced")
#define	PERMISSION_MSG			(sysinfo.japanesef ? "書き込み権がありません。":"Permission denied")
#define	DONT_WRITE_FILE_MSG		(sysinfo.japanesef ? "ファイルが書けません。":"Impossible to Write File")
#define	DONT_OPEN_MORE_FILE_MSG	(sysinfo.japanesef ? "これ以上開けません。":"No more Files Opened")
#define	FILE_EXIST_MSG			(sysinfo.japanesef ? "すでにファイルが存在します。":"File Exist")
#define	THIS_FILE_OPENED_MSG	(sysinfo.japanesef ? "既にオープンされています。":"This File Opened")
#define	THIS_FILE_CHANGED_MSG	(sysinfo.japanesef ? "このファイルは変更されていますが、保存しますか":"This file Changed. Do you save")
#define	SAVE_FILE_CHANGED_MSG	(sysinfo.japanesef ? "保存先のファイルがアクセスされてますが、保存しますか":"Target File is rewritten by other process. Do you save")
#define	TARGET_FILE_CHANGED_MSG	(sysinfo.japanesef ? "保存先のファイルがアクセスされてます。":"Target File is rewritten by other process. Do you save")
#define	TARGET_FILE_PERM_MSG	(sysinfo.japanesef ? "ファイルが読めなくなりました。":"Target file is changed permittion")
#define	ARE_YOU_SURE_MSG		(sysinfo.japanesef ? "このファイルは変更されていますが、よろしいですか":"This file Changed. Are You Sure")
#define	QUIT_ARE_YOU_SURE_MSG	(sysinfo.japanesef ? "このファイルは変更されていますが、終了してよろしいですか":"This file Changed. Are you sure you want to exit")
#define	LINE_BUFFER_OVER_MSG	(sysinfo.japanesef ? "行バッファがいっぱいです。":"Line Buffer Over Flow")
#define	GETS_FIND_MSG			(sysinfo.japanesef ? "検索文字列: ":"Find: ")
#define	GETS_REPLACE_MSG		(sysinfo.japanesef ? "置換文字列: ":"Replace With: ")
#define	GETS_SHELL_MSG			(sysinfo.japanesef ? "子プロセス: ":"Shell: ")
#define	RENAME_MSG				(sysinfo.japanesef ? "ファイル名の変更: ":"Rename file: ")
#define	OPEN_MSG				(sysinfo.japanesef ? "新規ファイル: ":"Open: ")
#define	INS_MSG					(sysinfo.japanesef ? "ファイル挿入: ":"Open: ")
#define	TYPE_EXIT_MSG			(sysinfo.japanesef ? "`exit' でもどります。":"Type `exit' to return")
#define	HIT_ANY_KEY_MSG			(sysinfo.japanesef ? "リターンを押してください。":"Hit Return Key")
#define	REPLACE_ALL_MSG			(sysinfo.japanesef ? "A)テキスト全体":"All Text")
#define	REPLACE_FORWARD_MSG		(sysinfo.japanesef ? "F)カーソル以降":"Forward Cursor")
#define	REPLACE_BACK_MSG		(sysinfo.japanesef ? "B)カーソル以前":"Back Cursor")
#define	REPLACE_INSIDEBLOCK_MSG	(sysinfo.japanesef ? "I)ブロック範囲":"Inside Block")
#define	DELETE_BLOCK_BUFFER_MSG	(sysinfo.japanesef ? "ブロックバッファが一杯です。削除しますか":"Block buffer is full. Do you want to delete it")
#define DELETE_YANK_BUFFER_MSG	(sysinfo.japanesef ? "ヤンクバッファを削除します。":"Delete the yank buffer")
#define UNABLE_OPEN_LOCK_FILE_MSG (sysinfo.japanesef ? "lock ファイルが open 出来ません。":"Unable to open lock file")
#define LOCK_FILE_LOCKED_MSG	(sysinfo.japanesef ? "lock ファイルが lock されています。":"Lock file is locked")
#define ALREADY_OPEN_MSG		(sysinfo.japanesef ? "既にオープンされています。":"It is already open")
#define ORIGINAL_ALSO_OPEN_MSG	(sysinfo.japanesef ? "元ファイルもオープンされています。":"Original file is also open")
#define UNKNOWN_ERROR_MSG		(sysinfo.japanesef ? "不明なエラーです。":"Unknown Error")
#define READ_ONLY_MSG			(sysinfo.japanesef ? "リードオンリーです。":"Read only")
#define PROCESS_MSG				(sysinfo.japanesef ? "Y) 処理する":"Y)Process")
#define NOT_PROCESS_MSG			(sysinfo.japanesef ? "N) 処理しない":"N)Do not process")
#define PROCESS_ALL_MSG			(sysinfo.japanesef ? "A) 以降全て処理する":"A)Everything after this is handled")
#define NOT_PROCESS_ALL_MSG		(sysinfo.japanesef ? "K) 以降全て処理しない":"K)Do not process anything after this")
#define OVERWRITE_ALL_MSG		(sysinfo.japanesef ? "O) 全て上書き":"Overwrite all")
#define NEWER_DATE_MSG			(sysinfo.japanesef ? "N) 新しい日付の場合":"Newer date")
#define SAME_NAME_NO_COPY_MSG	(sysinfo.japanesef ? "S) 同名はコピーしない":"Same name not copied")
#define RENAME_AND_COPY_MSG		(sysinfo.japanesef ? "R) 名前を変えてコピー":"Rename and copy")
#define ABORT_MSG				(sysinfo.japanesef ? "A) 中止":"Abort")
#define RETRY_MSG				(sysinfo.japanesef ? "R) 再試行":"Retry")
#define CONTINUE_MSG			(sysinfo.japanesef ? "C) 継続":"Continue")
#define NEW_NAME_MSG			(sysinfo.japanesef ? "新しい名前: ":"Rename: ")
#define DESTINATION_MSG			(sysinfo.japanesef ? "複写先: ":"destination: ")
#define CHANGE_DIR_MSG			(sysinfo.japanesef ? "移動先ディレクトリ: ":"Change Dir: ")
#define PATH_MASK_MSG			(sysinfo.japanesef ? "パス・マスク: ":"Path Mask: ")
#define MKDIR_MSG				(sysinfo.japanesef ? "作成ディレクトリ: ":"Mkdir: ")
#define COPY_MSG				(sysinfo.japanesef ? "複写":"Copy")
#define MOVE_MSG				(sysinfo.japanesef ? "移動":"Move")
#define DO_DELETE_MSG			(sysinfo.japanesef ? "削除します。よろしいでしょうか":"Do you want to delete it")
#define DELETE_MSG				(sysinfo.japanesef ? "削除":"Delete")
#define KEYMACRO_ERROR_MSG		(sysinfo.japanesef ? "KeyMacro エラー %.20s":"KeyMacro Error %.20s")
#define KEYMACRO_SET_MSG		(sysinfo.japanesef ? "KeyMacro を %.4s にセットしました。":"KeyMacro set to %.4s")
#define SETTING_KEYMACRO_MSG	(sysinfo.japanesef ? "KeyMacro 設定中":"Setting KeyMacro")
#define KEYMACRO_RUNNING_MSG	(sysinfo.japanesef ? "KeyMacro 起動中":"KeyMacro running")
#define LINE_NUMBER_MSG			(sysinfo.japanesef ? "行番号: ":"Line number: ")
#define REPLACE_YNA_MSG			(sysinfo.japanesef ? "置換しますか? (Y/N/A): ":"Replace? (Y/N/A): ")
#define ENVIRONMENT_VARIABLE_MSG (sysinfo.japanesef ? "環境変数:\n":"Environment variable:\n")
#define DIR_ALREADY_FILE_MSG	(sysinfo.japanesef ? "ディレクトリと同名のファイルが存在します。":"A file with the same name as the directory already exists")


#define	MENU_OPEN_MSG			(sysinfo.japanesef ? "O)ファイルのオープン":"Open")
#define	MENU_CLOSE_MSG			(sysinfo.japanesef ? "C)ファイルのクローズ":"Close current file")
#define	MENU_SAVE_MSG			(sysinfo.japanesef ? "S)ファイルの保存":"Save")
#define	MENU_SAVEAS_MSG			(sysinfo.japanesef ? "A)ファイル名を変えて保存":"Save as")
#define	MENU_CLOSE_AF_MSG		(sysinfo.japanesef ? "X)全ファイルのクローズ":"Close all files")
#define	MENU_RENAME_MSG			(sysinfo.japanesef ? "R)ファイル名の変更":"Rename file")
#define	MENU_REFRESH_CF_MSG		(sysinfo.japanesef ? "U)編集のやり直し":"Refresh current file")
#define	MENU_ESCAPE_SHELL_MSG	(sysinfo.japanesef ? "E)子プロセス":"Escape Shell")
#define	MENU_INSERT_OUTPUT_MSG	(sysinfo.japanesef ? "G)子プロセスの出力を取り込み":"Exec and insert output")

#define	OPT_NUMBER_MSG			(sysinfo.japanesef ? "N)行番号                 : ":"Number                   : ")
#define	OPT_INPUT_MODE_MSG		(sysinfo.japanesef ? "O)オーバーライト         : ":"Over Write               : ")
#define	OPT_AUTOINDENT_MODE_MSG	(sysinfo.japanesef ? "A)オートインデント       : ":"AutoIndent               : ")
#define	OPT_BACKUP_MSG			(sysinfo.japanesef ? "B)バックアップ           : ":"BackUp                   : ")
#define	OPT_TAB_MARK_MSG		(sysinfo.japanesef ? "M)タブマーク             : ":"M)Tab Mark               : ")
#define	OPT_CR_MARK_MSG			(sysinfo.japanesef ? "C)行末マーク             : ":"Cr Mark                  : ")
#define	OPT_SEARCH_CH_MSG		(sysinfo.japanesef ? "S)検索時の大／小文字     : ":"Search String            : ")
#define	OPT_MESSAGE_MSG			(sysinfo.japanesef ? "J)日本語メッセージ       : ":"Japanese Message         : ")
#define	OPT_KANJICODE_MSG		(sysinfo.japanesef ? "K)漢字コード             : ":"Kanji Code               : ")
#define	OPT_AMBIGUOUS_MSG		(sysinfo.japanesef ? "W)曖昧文字幅             : ":"W)Ambiguous char width   : ")
#define	OPT_TAB_STOP_MSG		(sysinfo.japanesef ? "T)タブストップ数         : ":"Tab Stop                 : ")
#define	OPT_PASTE_MOVE_MSG		(sysinfo.japanesef ? "V)ペーストでカーソル移動 : ":"V)Paste to move cursor   : ")
#define	OPT_UNDERLINE_MSG		(sysinfo.japanesef ? "U)アンダーライン表示     : ":"Underline                : ")

#define	FILE_COPY_MSG			(sysinfo.japanesef ? "C)コピー":"Copy")
#define	FILE_MOVE_MSG			(sysinfo.japanesef ? "M)移動":"Move")
#define	FILE_DELETE_MSG			(sysinfo.japanesef ? "D)削除":"Delete")
#define	FILE_RENAME_MSG			(sysinfo.japanesef ? "R)名前の変更":"Rename")
#define	FILE_MKDIR_MSG			(sysinfo.japanesef ? "K)ディレクトリ作成":"K)Mkdir")
#define	FILE_EXEC_MSG			(sysinfo.japanesef ? "X)子プロセス実行":"X)Execute")
#define	FILE_NEW_MSG			(sysinfo.japanesef ? "N)新規ファイル作成":"New file")

#define	SORT_FILENAME_MSG		(sysinfo.japanesef ? "F)ファイル名":"Filename")
#define	SORT_EXT_MSG			(sysinfo.japanesef ? "E)拡張子":"Ext")
#define	SORT_NEW_MSG			(sysinfo.japanesef ? "N)新しい順":"New")
#define	SORT_OLD_MSG			(sysinfo.japanesef ? "O)古い順":"Old")
#define	SORT_LARGE_MSG			(sysinfo.japanesef ? "L)大きい順":"Large")
#define	SORT_SMALL_MSG			(sysinfo.japanesef ? "S)小さい順":"Small")
