void se_insert(const char *s, int f);
void se_delete(int n, int f);
void undo_paste();
void undo_add(int df, const char *s);
void udbuf_set(int df, const char *s);
void udbuf_get(char *s);
void udbuf_init();
void lm_mark(int ln, int n);
int lm_line(int n);
int CatLine();
