#ifndef	__SH_DEF_H_
#define	__SH_DEF_H_

#define	MAX_region	3
#define	MAX_func	68

enum {
	 KF_cursor_up,
	 KF_cursor_down,
	 KF_cursor_left,
	 KF_cursor_right,
	 KF_cursor_tkprev,
	 KF_cursor_tknext,
	 KF_cursor_sleft,
	 KF_cursor_sright,
	 KF_cursor_sup,
	 KF_cursor_sdown,
	 KF_cursor_top,
	 KF_cursor_bottom,
	 KF_cursor_pup,
	 KF_cursor_pdown,
	 KF_cursor_rup,
	 KF_cursor_rdown,
	 KF_jump_before,
	 KF_jump_mark,
	 KF_jump_line,
	 KF_jump_tag,
	 KF_char_input,
	 KF_char_undo,
	 KF_line_cr,
	 KF_line_new,
	 KF_line_undo,
	 KF_del_bs,
	 KF_del_char,
	 KF_del_tkprev,
	 KF_del_tknext,
	 KF_del_sleft,
	 KF_del_sright,
	 KF_opt_set,
	 KF_opt_linenum,
	 KF_opt_kanji,
	 KF_opt_retmode,
	 KF_opt_tab,
	 KF_misc_kmacro,
	 KF_misc_exec,
	 KF_misc_redraw,
	 KF_misc_insert_output,
	 KF_menu_opt,
	 KF_menu_file,
	 KF_block_start,
	 KF_block_cut,
	 KF_block_paste,
	 KF_block_yanc,
	 KF_block_copy,
	 KF_block_kill,
	 KF_block_dup,
	 KF_block_chlast,
	 KF_search_in,
	 KF_search_repl,
	 KF_search_repl_redo,
	 KF_search_prev,
	 KF_search_next,
	 KF_search_getword,
	 KF_search_paging,
	 KF_file_toggle,
	 KF_file_select,
	 KF_file_open,
	 KF_file_insert,
	 KF_file_close,
	 KF_file_save,
	 KF_file_aclose,
	 KF_file_copen,
	 KF_file_undo,
	 KF_file_rename,
	 KF_file_quit
};

enum {
	 KF_SysScrolldown,
	 KF_SysScrollup,
	 KF_SysRollup,
	 KF_SysRolldown,
	 KF_SysReturn,
	 KF_SysBackspace,
	 KF_SysDeletechar,
	 KF_SysCntrlInput,
	 KF_SysCursorupside,
	 KF_SysCursordownside,
	 KF_SysCursorleftside,
	 KF_SysCursorrightside,
	 KF_SysCursortopside,
	 KF_SysCursorendside,
	 KF_SysCursorup,
	 KF_SysCursordown,
	 KF_SysCursorleft,
	 KF_SysCursorright,
	 KF_SysEscape
};

enum {
	 KF_EffCursorUp,
	 KF_EffCursorDown,
	 KF_EffPageUp,
	 KF_EffPageDown,
	 KF_EffRollUp,
	 KF_EffRollDown,
	 KF_EffWindowChange,
	 KF_EffWindowNumChange,
	 KF_EffReRead,
	 KF_EffRename,
	 KF_EffMkdir,
	 KF_EffExec,
	 KF_EffMarkChange,
	 KF_EffMarkChangeAll,
	 KF_EffFileCp,
	 KF_EffFileMv,
	 KF_EffFileRm,
	 KF_EffBackSpace,
	 KF_EffChangeDir,
	 KF_EffRootDir,
	 KF_EffHomeDir,
	 KF_EffReturn,
	 KF_EffEscape
};

#endif
